name: Run actionlint on GitHub workflows

on:
  push:

  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Nix
        uses: ./actions/setup-nix
        with:
          use-magic-cache: "true"
      
      - name: Export direnv environment
        uses: ./actions/direnv-export

      - name: Lint GitHub workflows
        run: actionlint -color
